from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from src.domains.value import FormulaValue, LetterValue, NumberValue

    from .cell import TypeCellDependencies, TypeCellDependents

type TypeCellFormula = FormulaValue | None


class CellProtocol(Protocol):
    def __init__(self, value: "NumberValue", letter: "LetterValue") -> None: ...

    @property
    def value(self) -> "NumberValue": ...
    @value.setter
    def value(self, value: "NumberValue") -> None: ...
    @property
    def formula(self) -> "TypeCellFormula": ...
    @property
    def dependents(self) -> "TypeCellDependents": ...
    @property
    def dependencies(self) -> "TypeCellDependencies": ...

    def remove_dependent(self, letter: "LetterValue") -> None: ...

    # def set_formula(
    #     self, formula: Callable, dependencies: "MutableSequence[Cell]"
    # ) -> None: ...
    # def recalculate(self) -> None: ...

    # def set_formula(self, formula: str, ast_tree: "ASTNode") -> None: ...
    # def unlink_dependencies(self) -> None: ...
