from typing import TYPE_CHECKING, Protocol, Self

if TYPE_CHECKING:
    from ._types import TypeCellDependencies, TypeFormula


class Port[T](Protocol):
    @classmethod
    def new(cls, row: int, col: int) -> Self: ...
    @property
    def value(self) -> T | None: ...
    @value.setter
    def value(self, value: T) -> None: ...
    @property
    def dependents(self) -> "TypeCellDependencies": ...
    def set_formula(
        self, formula: "TypeFormula", dependencies: "TypeCellDependencies"
    ) -> None: ...
    def recalculate(self) -> None: ...
