from collections.abc import Callable, MutableSequence
from typing import Any, Protocol, Self


class TableProtocol(Protocol):
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def rows(self) -> int: ...
    @property
    def columns(self) -> int: ...
    def get_value(self, row: int, col: int) -> Any: ...  # noqa: ANN401


# class LayoutProtocol(Protocol):
#     @property
#     def columns(self) -> int: ...
#     def is_valid_table(self, sheet: TableProtocol) -> None: ...


class CellProtocol[T](Protocol):
    @classmethod
    def create_empty(cls) -> Self: ...
    @property
    def value(self) -> T | None: ...
    @value.setter
    def value(self, value: T) -> None: ...
    def set_formula(
        self,
        formula: Callable | None,
        dependencies: "MutableSequence[CellProtocol]",
    ) -> None: ...
    def recalculate(self) -> None: ...
